### ISSUE TITLE
I18N & Locale API

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-time-picker-flow#2]
Add the API and demos for handling localization, both setting of the time format with locale and the I18N object.

**Comment by ZheSun88** [comment]
I am returning this ticket to the sprint backlog.  because I am not sure what i can do with providing this support:
- with `i18n`: 
There are two functions, `formatTime` and `parseTime`, in the object, together with property `selector`, for me it looks this property is not ready to use, as i set it with the webcomponent, i didn't get the expected behavior.  
for the support those two functions, we can put getters and setters for them, but do we want the user the put arbitrary `String` for it, or what type of parameters should it be?

- With `locale`:
We can provide a similar connector, like the one we used for `date-picker`, but which js function should we use for it, i found one, `Date.prototype.toLocaleTimeString()`, which is also similar to the one used in `date-picker`. But there is one problem with this JS function, it cannot support the time format `hh:mm:ss.fff`.

**Comment by pleku** [comment]
As discussed f2f, what we really need in terms of the server side user is:
- a way to set the desired resolution: hour, minute, second, millisecond (similar to https://github.com/vaadin/vaadin-time-picker/issues/42)
- a way to set the desired locale, which applies either the 12/24 hours clock to the component
  - by default, the locale is picked up from the UI

**Comment by ZheSun88** [comment]
After this, release `vaadin-time-picker-flow`, 1.0.0.beta1, which is based on `flow` 1.0.X and `flow-component-base` 1.0.X
